spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/credit
    username: root
#    password: postgres
logging:
  level:
    io.r2dbc.postgresql.QUERY: DEBUG # for queries
    io.r2dbc.postgresql.PARAM: DEBUG # for parameters